### ISSUE TITLE
Can't open with visual studio 2019

### ISSUE THREAD

**Issue by mingyEx** [strobejb/Neatpad#1]
Hello, I am reading your blog：
http://www.catch22.net/tuts/neatpad/neatpad-overview
I encountered an error when trying to open https://github.com/strobejb/Neatpad with visual studio 2019:
Neatpad\Neatpad.dsp: Unable to convert project. Please make sure this is a valid Visual C++ 6.0 project.
Neatpad\Neatpad.dsp: Project upgrade failed.
TextView\TextView.dsp: Unable to convert project. Please make sure this is a valid Visual C++ 6.0 project.
TextView\TextView.dsp: Project upgrade failed.
UspLib\UspLib.dsp: Unable to convert project. Please make sure this is a valid Visual C++ 6.0 project.
UspLib\UspLib.dsp: Project upgrade failed.
Can you upgrade it to the latest version?

**Comment by mingy532** [comment]
and I cannot compile the sourcecode in http://www.catch22.net/tuts/neatpad/unicode-text-processing#
because it said:
```
SPI_GETCARETWIDTH': undeclared identifier	TextView	C:\xxxNeatpad09\TextView\TextView.cpp	50	
```
I read the msdn and add #include<WinUser.h> but still it exist ,I don't know how to do ...
I try google SPI_GETCARETWIDTH and find nothing.

**Comment by mingy532** [comment]
I download vs2010 and vs2008 do as this :
https://stackoverflow.com/questions/9444618/how-can-i-convert-a-project-from-visual-c-6-0-to-visual-studio-express-2010
but it show:
```
The project is damaged and cannot be loaded
```

**Comment by mingy532** [comment]
I download every zip file in http://www.catch22.net/tuts/neatpad/loading-text-file# and occur error as follow:
```
Error (active)	E0020	identifier "CLEARTYPE_QUALITY" is undefined	Neatpad	C:\Users\mingy\Desktop\Neatpad06\Neatpad\OptionsFont.c	741	


Error C1083	Cannot open source file: '..\..\..\common\Trace.c': No such file or directory	TextView	C:\Users\mingy\Desktop\Neatpad07\TextView\c1	1	

Error (active)	E0020	identifier "SPI_GETCARETWIDTH" is undefined	TextView	C:\Users\mingy\Desktop\Neatpad09\TextView\TextView.cpp	50	


Error	C1189	#error:  "Please build as Unicode only!"	TextView	C:\Users\mingy\Desktop\Neatpad15\TextView\TextView.cpp	17	

Error	C2065	'CLEARTYPE_QUALITY': undeclared identifier	Neatpad	C:\Users\mingy\Desktop\Neatpad15\Neatpad\OptionsFont.c	779	

Error	C1189	#error:  "Please build as Unicode only!"	Neatpad	C:\Users\mingy\Desktop\Neatpad15\Neatpad\Neatpad.c	18	


Error	C2664	'BOOL UspAnalyze(USPDATA *,HDC,WCHAR *,int,ATTR *,UINT,USPFONT *,SCRIPT_CONTROL *,SCRIPT_STATE *,SCRIPT_TABDEF *)': cannot convert argument 3 from 'TCHAR [128]' to 'WCHAR *'	TextView	C:\Users\mingy\Desktop\Neatpad18\TextView\TextViewPaint.cpp	105	

Error	C2664	'ULONG TextView::EnterText(TCHAR *,ULONG)': cannot convert argument 1 from 'WCHAR *' to 'TCHAR *'	TextView	C:\Users\mingy\Desktop\Neatpad18\TextView\TextViewKeyInput.cpp	270	

Warning		UNICODE is not defined	Neatpad	C:\Users\mingy\Desktop\Neatpad18\Neatpad\CL	1	
Error	C1189	#error :  "Please build as Unicode only!"	Neatpad	C:\Users\mingy\Desktop\Neatpad18\Neatpad\Neatpad.c	23	
```

**Comment by mingy532** [comment]
I know that win32 is outdated, and now no one wants to learn
However, when one encounter some problems, you must understand its code.
And I‘m very interested in what you write.
After consulting some documents, it still can't be solved, thank you if you can help
